### ISSUE TITLE
[Bug 🐞]: Fairings and tweakscale

### ISSUE THREAD

**Issue by EndAllFilms** [zer0Kerbal/SeaDragon#49]
### Brief description of your issue (aka the problem)

There is a bug where the more you make it big by using tweak scale the more the fairing shells are most likely to be bugged out

### Operating system

Windows 11

### KSP version

1.12.4 The Latest Version

### Version of addon

Version 0.3.4.0

### Steps to reproduce the behavior or issue

I don't know

### Expected behavior

I thought the fairing was supposed to be detailed

### Actual behavior

[KSP.log](https://github.com/zer0Kerbal/SeaDragon/files/9991710/KSP.log)

### Environment

```shell
Mod: Real Scale Sea Dragon
KSP: 1.12.4 Latest Version
Download: CKAN
```

### Screenshots

![image](https://user-images.githubusercontent.com/112870117/201387017-0c730818-d16f-4935-bd27-87181d35ed56.png)

### How did you download and install this?

CKAN (auto install with dependencies)

**Comment by zer0Kerbal** [comment]
@EndAllFilms Thank you for the report.
Am looking into this
 Have reached out to the author of Tweakscale.
